version: "3.7"
name: "saveworld"
services:
  redis:
    image: "redis:alpine"
    restart: unless-stopped
    networks:
      - saveworld
  translate_server:
    build:
      context: "./translate-server"
      dockerfile: "Dockerfile"
    restart: unless-stopped
    ports:
      - "8800:3000"
    networks:
      - saveworld
  translate_cache:
    build:
      context: "./translate-cache"
      dockerfile: "Dockerfile"
    ports:
      - "8801:3000"
    environment:
      - REDIS_URL=redis://redis:6379
    restart: unless-stopped
    depends_on:
      - translate_server
      - redis
    networks:
      - saveworld
networks:
  saveworld:
    name: saveworld
    driver: bridge
