/**
 * backend2/src/util/Perms.ts
 *
 * Author: Ben Siebert <hello@ben-siebert.de>
 * Copyright: Copyright (c) 2018-2024 Ben Siebert. All rights reserved.
 * License: Project License
 * Created At: 10.03.2024
 *
 */

export enum Perms {
  ADMIN_PANEL = "admin.panel",
  AI_SINGLE_REQUEST = "ai.single_request",
  AI_CHAT_REQUEST = "ai.chat_request",
  COMMUNITY_SUGGESTED = "community.suggested",
  COMMUNITY_SEARCH = "community.search",
  COMMUNITY_FOLLOWING = "community.following",
  COMMUNITY_COMMENT = "community.comment",
  COMMUNITY_CREATE_BLOG = "community.create.blog",
  COMMUNITY_DELETE_BLOG = "community.delete.blog",
  COMMUNITY_LIKE = "community.like",
  COMMUNITY_RECEIVE_BLOG = "community.receive.blog",
  COMMUNITY_RECEIVE_PROFILE = "community.receive.profile",
  COMMUNITY_FOLLOW = "community.follow",
  COMMUNITY_RECEIVE_PROFILE_BLOGS = "community.receive.profile.blogs",
  CONTENT_VIDEOS_SUGGESTED = "content.videos.suggested",
  CONTENT_VIDEOS_HISTORY = "content.videos.history",
  CONTENT_VIDEOS_COMMENT = "content.videos.comment",
  CONTENT_VIDEOS_COMMENTS = "content.videos.comments",
  EATINGPLAN_GET = "eatingplan.get",
  EATINGPLAN_CREATE = "eatingplan.create",
  EATINGPLAN_UPDATE = "eatingplan.update",
  EATINGPLAN_DELETE = "eatingplan.delete",
  E2PROJECTS_MY = "e2projects.my",
  E2PROJECTS_CREATE = "e2projects.create",
  E2PROJECTS_TOGGLE_MEMBER = "e2projects.toggle_member",
  E2PROJECTS_UPDATE = "e2projects.update",
  E2PROJECTS_DELETE = "e2projects.delete",
  E2PROJECTS_TODO_LISTS = "e2projects.todo.lists",
  E2PROJECTS_TODO_LISTS_CREATE = "e2projects.todo.lists.create",
  E2PROJECTS_TODO_LIST_DELETE = "e2projects.todo.list.delete",
  E2PROJECTS_TODO_ITEMS = "e2projects.todo.items",
  E2PROJECTS_TODO_ITEM_DELETE = "e2projects.todo.item.delete",
  E2PROJECTS_TODO_ITEM_CREATE = "e2projects.todo.item.create",
  E2PROJECTS_TODO_ITEM_CHECK = "e2projects.todo.item.check",
  E2PROJECTS_MEMBER_DELETE = "e2projects.members.delete",
  E2PROJECTS_MEMBER_CHANGE_ROLE = "e2projects.members.change_role",
  GAMES_LEADERBOARD = "games.leaderboard",
  LIFESTYLE_MY = "lifestyle.my",
  LIFESTYLE_LEVEL = "lifestyle.level",
  LIFESTYLE_SUBMIT = "lifestyle.submit",
  LIFESTYLE_UPDATE = "lifestyle.update",
  LIFESTYLE_MY_WEEKLY = "lifestyle.my.weekly",
  LIFESTYLE_MY_DAY = "lifestyle.my.day",
  NOTIFICATIONS_MY = "notifications.my",
  NOTIFICATIONS_READ = "notifications.read",
  RECIPES_ALL = "recipes.all",
  RECIPES_CREATE = "recipes.create",
  RECIPES_DELETE = "recipes.delete",
  RECIPES_MY = "recipes.my",
  RECIPES_RECEIVE = "recipes.receive",
  RECIPES_UPDATE = "recipes.update",
  SCHOOL_CLASSES_RECEIVE = "school.classes.receive",
  SCHOOL_CLASSES_CREATE = "school.classes.create",
  SCHOOL_CLASSES_UPDATE = "school.classes.update",
  SCHOOL_CLASSES_DELETE = "school.classes.delete",
}
