name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build backend --file backend/Dockerfile --tag registry.ben-siebert.com/ben/saveworld-backend:latest && docker push registry.ben-siebert.com/ben/saveworld-backend:latest
